name: Terraform deploy webserver

on:
  workflow_dispatch:

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -var "subnet_id=${{ secrets.subnet_id }}" -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}"

      - name: Terraform apply
        run: terraform apply -auto-approve -var "subnet_id=${{ secrets.security_group_id }}" -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}"
